server:
  port: 8804

app:
  druid:
    username: druid
    password: 123456
    reset-all: true

spring:
  application:
    name: biz-api-service
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9998
  datasource:
    druid:
      url: jdbc:mysql://39.106.180.50:3306/enterprise
      username: samuel778
      password: q19911002
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池配置
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 10000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall #filters: # 配置多个英文逗号分隔(统计，sql注入，log4j过滤)
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6378
      # Redis服务器连接密码（默认为空）
      password: hTReds_0522
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 30
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 30
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接超时时间（毫秒）
          timeout: 6000

logging:
  level:
    com.micro.domain : debug

